# Generated by Django 4.2.5 on 2024-03-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_well_number", models.CharField(max_length=255, unique=True)),
                ("oil", models.IntegerField()),
                ("gas", models.IntegerField()),
                ("brine", models.IntegerField()),
            ],
        ),
    ]
